baseURL = 'https://www.sumitdhiman.in'
languageCode = 'en-us'
publishDir = "docs"

[markup.goldmark.renderer]
  unsafe= true

loading="lazy"
enableRobotsTXT = true

[sitemap]
  ChangeFreq = "daily"
  Priority = "1"

[markup]
taskLists = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true 
    hl_Lines = 'x'
    hl_inline = false 
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = true
    style = 'rose-pine-moon'
    tabWidth = 4

[menu]
  [[menu.header]]
    name = "Résumé"
    weight = 5
    url = "resume/"
  [[menu.header]]
    name = "About"
    weight = 4
    url = "about"
  [[menu.header]]
    name = "Blog"
    weight = 3
    url = "blog"
  [[menu.header]]
    name = "Projects"
    weight = 2
    url = "projects"
  [[menu.header]]
    name = "Home"
    weight = 1
    url = "/"
[params]
author = "Sumit Dhiman"
user = "sumit"
hostname = "portfolio"
search=true
search_minify=true

[[params.social]]
key = 0
name = "github"
url = "https://github.com/lucifer1708"
icon = "fa-brands fa-github"

[[params.social]]
key = 2
name = "linkedin"
url = "https://linkedin.com/in/sumit-dhiman-20bce091"
icon = "fa-brands fa-linkedin"

[[params.social]]
key = 3
name = "email"
url = "mailto:hello@sumitdhiman.in"
icon ="fa-solid fa-envelope"


[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML', 'RSS']
