baseURL = 'http://example.site'
languageCode = 'en-us'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "Blog"
    weight = 2
    url = "blog"
  [[menu.header]]
    name = "About"
    weight = 2
    url = "about"
  [[menu.header]]
    name = "Projects"
    weight = 2
    url = "/projects"
  [[menu.header]]
    name = "Resume"
    weight = 0
    url = "/resume"

[params]
author = "Sumit Dhiman"
user = "lucifer"
hostname = "protfolio"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/lucifer1708"
icon = "fa-brands fa-github"

[[params.social]]
key = 2
name = "linkedin"
url = "https://linkedin.com/in/20bce091-sumit-dhiman"
icon = "fa-brands fa-linkedin"

[[params.social]]
key = 3
name = "email"
url = "mailto:sd08012003@gmail.com"
icon = "fa-solid fa-envelope"
