baseURL = 'http://lucifer1708.github.io/'
languageCode = 'en-us'
publishDir = "docs"

[menu]
  [[menu.header]]
    name = "Resume"
    weight = 4
    url = "resume"
  [[menu.header]]
    name = "About"
    weight = 3
    url = "about"
  [[menu.header]]
    name = "Blog"
    weight = 2
    url = "blog"
  [[menu.header]]
    name = "Projects"
    weight = 1
    url = "projects"

[params]
author = "Sumit Dhiman"
user = "sumit"
hostname = "portfolio"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/gohugoio"
icon = "fa-brands fa-github"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.example.com"
icon = "fa-brands fa-linkedin"

[[params.social]]
key = 3
name = "email"
url = "mailto:email@example.com"
icon ="fa-solid fa-envelope"
